name: serial_port
version: 0.2.4-dev
description: Dart extension library to communicate on serial port.
author: Nicolas Francois  <nicolas.franc@gmail.com>
homepage: https://github.com/nfrancois/serial_port
environnment:
  sdk: '>=1.9.1 <2.0.0'
dependencies:
  ccompile: ">=0.2.8 <0.3.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
